export const CLIMATE_SEARCH = 'CLIMATE_SEARCH';
export const CLIMATE_SEARCH_SUCCESS = 'CLIMATE_SEARCH_SUCCESS';
export const CLIMATE_SEARCH_FAILED = 'CLIMATE_SEARCH_FAILED';
export const UPDATE_CITY = 'UPDATE_CITY';
export const SHOW_BUTTON_SEARCH = 'SHOW_BUTTON_SEARCH';